version: 2.1

jobs:
  build:
    working_directory: ~/ngrx-auto-entity
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: NODE_ENV=ci npm ci --silent
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Run tests (with JUnit output)
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
